//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APINJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int U_Id { get; set; }
        public string U_Name { get; set; }
        public string U_Apellidos { get; set; }
        public string U_Email { get; set; }
        public string U_Nick { get; set; }
        public string U_Pass { get; set; }
        public string U_Status { get; set; }
        public string U_Gender { get; set; }
    }
}
